# Generated by Django 5.0.3 on 2024-03-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotifytoken", old_name="acces_token", new_name="access_token",
        ),
    ]
